### PR TITLE
Update ssb-private

### PR DESCRIPTION
**Pull request by christianbundy**
This upgrade removes the dependency on leveldown@1.7.2, which may help with resolving https://github.com/ssbc/patchbay/issues/224, but unfortunately the output of `npm test` doesn't look good. It's *technically* returning a successful error code, but it doesn't look like success to me.

```console
$ npm test

> scuttle-invite@1.0.1 test /home/christianbundy/Source/scuttle-invite
> tape test/**/*.test.js | tap-diff


  invites.async.canReply: Cannot reply to one's self
/home/christianbundy/Source/scuttle-invite/invites/async/canReply.js:5
    let otherRecp = recps.find(recp => recp !== server.id)
                          ^

TypeError: Cannot read property 'find' of undefined
    at canReply (/home/christianbundy/Source/scuttle-invite/invites/async/canReply.js:5:27)
    at publishInvite (/home/christianbundy/Source/scuttle-invite/test/async/canReply.test.js:33:24)
    at Array.<anonymous> (/home/christianbundy/Source/scuttle-invite/node_modules/secure-scuttlebutt/minimal.js:175:9)
    at Function.queue.onDrain (/home/christianbundy/Source/scuttle-invite/node_modules/secure-scuttlebutt/minimal.js:109:17)
    at /home/christianbundy/Source/scuttle-invite/node_modules/async-write/index.js:24:55
    at Object.cb (/home/christianbundy/Source/scuttle-invite/node_modules/secure-scuttlebutt/minimal.js:93:7)
    at /home/christianbundy/Source/scuttle-invite/node_modules/append-batch/index.js:22:38
    at /home/christianbundy/Source/scuttle-invite/node_modules/flumelog-offset/inject.js:27:9
    at /home/christianbundy/Source/scuttle-invite/node_modules/aligned-block-file/blocks.js:172:13
    at /home/christianbundy/Source/scuttle-invite/node_modules/aligned-block-file/file.js:62:13

passed: 0  failed: 0  of 0 tests  (385ms)

All of 0 tests passed!
```

Any ideas on what may need to change to get this error resolved?

### CODE REVIEW

**Comment by christianbundy** [comment]
Wait, I just switched to Node LTS Carbon (v8.11.3) and I'm still getting the same results. Maybe the tests are just broken?

**Comment by christianbundy** [comment]
Please disregard both of the above, those were just caused by running `npm audit fix`, which isn't actually necessary for this PR.

I've force-pushed a commit which upgrades ssb-private and resolves the Node 10 compatibility issue, and this PR should be ready to merge.

**Comment by arj03** [comment]
+1. old private has a nasty security hole as well.

**Comment by mixmix** [comment]
thanks, published as `1.0.3`

note that ssb-private was only being used in tests - all these scuttle-modules just accept a `server` and then use the plugins there like `server.private`

I've moved ssb-private to a dev-dep.
~~I'm gonna add you to ssbc on github generally to make PRs easier. Also thanks for all your contributions and tidying, I really appreciate the attention and care~~

EDIT - you were already added, I guess this PR was from before then

**Comment by christianbundy** [comment]
Thanks @mixmix -- I was added a couple of days ago by @ahdinosaur. :upside_down_face: 

Now that I'm in the ssbc org I've just been pushing branches as `foo` or `@christianbundy/foo`, but still doing my regular development flow (branch off master, open a PR, await review). Is that how I should still be working? I don't want to abuse `master` by merging branches willy nilly, but I'm also hesitant to keep adding code to the review pile and creating a backlog of work for others to review. We can also discuss on SSB if that's better than on a random PR.

**Pull request merged**
